---
title: "FA2_DMAW"
author: "MORILLO, JADE MARCO S."
date: "2025-02-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(stringi)
```

```{r 2.1.preview}
data("who")
data("population")

head(who)
head(population)
```

```{r 2.2. import}
who <- as_tibble(who)
population <- as_tibble(population)
```

```{r 2.3. dimensions}
dim(who)
dim(population)
```

```{r 2.4. summary}
summary(population)

```

3.1 WHO dataset

```{r 3.1.1. variables}
glimpse(who)
```

```{r 3.1.2. pivot}
who2 <- who %>%
  pivot_longer(cols = starts_with("new_"), names_to = "cases_type", values_to = "cases", values_drop_na = TRUE) %>%
  mutate(cases = as.numeric(cases)) 
```

```{r 3.1.3. separate to who3}
who3 <- who2 %>%
  separate(cases_type, into = c("new", "tb_type", "sex_age"), sep = "_") %>%
  select(-new)
```

```{r 3.1.4. separate to who_tidy}
who_tidy <- who3 %>%
  separate(sex_age, into = c("sex", "age_group"), sep = 1)
```

3.2. POPULATION Dataset

```{r 3.2.1. identify}
glimpse(population)
```

```{r 3.2.2. pivot}
population3 <- population %>%
  pivot_longer(cols = -country, names_to = "year", values_to = "population")
```

```{r 3.2.3. cast}
population_tidy <- population3 %>%
  mutate(year = as.integer(year), population = as.numeric(population))
```

3.3. Join Datasets

```{r 3.3.1. identify}
names(who_tidy)
names(population_tidy)
```

```{r 3.3.2. rename}
population <- population %>%
  rename(country_name = country)
```

```{r 3.3.3. join_into_tibble}
who_tidy <- who_tidy %>%
  mutate(country = str_to_lower(stri_trans_general(country, "Latin-ASCII")))

population <- population %>%
  mutate(country_name = str_to_lower(stri_trans_general(country_name, "Latin-ASCII")))

tuberculosis <- who_tidy %>%
  left_join(population, by = c("country" = "country_name", "year" = "year"))
```

3.4. Clean Up Data

```{r 3.4.1. remove}
tuberculosis <- tuberculosis %>%
  select(country, iso2, iso3, year, tb_type, sex, age_group, cases, population)
```

```{r 3.4.2. filter}
tuberculosis <- tuberculosis %>%
  drop_na()
```

```{r 4.1. determine}
us_cases <- tuberculosis %>%
  filter(str_detect(str_to_lower(country), "united states of america"), year >= 2000) %>%
  group_by(sex) %>%
  summarise(total_cases = sum(cases, na.rm = TRUE)) %>%
  arrange(desc(total_cases))

us_cases
```

```{r 4.2. cases_per_100k}
tuberculosis <- tuberculosis %>%
  mutate(cases_per_100k = ifelse(population == 0 | is.na(population), NA, (cases / population) * 100000))
```

```{r 4.3. highest_lowest}
highest_cases <- tuberculosis %>%
  filter(!is.na(cases_per_100k)) %>%
  arrange(desc(cases_per_100k)) %>%
  slice(1)

lowest_cases <- tuberculosis %>%
  filter(!is.na(cases_per_100k)) %>%
  arrange(cases_per_100k) %>%
  slice(1)

highest_cases
lowest_cases
```

```{r 5.1. plot}
tuberculosis %>%
  filter(str_to_lower(country) %in% c("china", "india", "united states")) %>%
  group_by(country, year) %>%
  summarise(total_cases_per_100k = sum(cases_per_100k, na.rm = TRUE)) %>%
  ggplot(aes(x = year, y = total_cases_per_100k, color = country)) +
  geom_line() +
  scale_y_log10() +
  labs(title = "TB Cases per 100k Over Time", y = "Cases per 100k (log scale)")
```

```{r 5.2. compare}
tuberculosis %>%
  group_by(age_group) %>%
  summarise(total_cases_per_100k = sum(cases_per_100k, na.rm = TRUE)) %>%
  ggplot(aes(x = age_group, y = total_cases_per_100k)) +
  geom_bar(stat = "identity") +
  scale_y_log10() +
  labs(title = "TB Cases per 100k by Age Group")
```

```{r 5.3. conclude}
tuberculosis %>%
  filter(year == 2000) %>%
  ggplot(aes(x = population, y = cases_per_100k)) +
  geom_point(alpha = 0.5) +
  scale_x_log10() +
  scale_y_log10() +
  labs(title = "TB Cases per 100k vs. Population (2000)")
```